### ISSUE TITLE
@typescript-eslint/indent is conflicting with editorconfig/indent

### ISSUE THREAD

**Issue by xymopen** [phanect/eslint-plugin-editorconfig#44]
[@typescript-eslint/eslint-plugin](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin) has their own version of [`@typescript-eslint/indent`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/indent.md) which is conflicting with ours. It should also be added into the `noconflict` config.

**Comment by phanect** [comment]
This issue should be resolved in v3.2.0.
