### ISSUE TITLE
Unexpected tab character

### ISSUE THREAD

**Issue by klim-neumann** [phanect/eslint-plugin-editorconfig#56]
<img width="491" alt="image" src="https://user-images.githubusercontent.com/114701548/200188148-fbac5453-05e0-4f6b-9d00-f5081ddadc7a.png">

Plugin conflicts with eslint 'no-tabs' rule.

.editorconfg
```
root = true

[*]
trim_trailing_whitespace = true
insert_final_newline = true
end_of_line = lf
charset = utf-8

[*.{html,css,js,json}]
indent_style = tab
tab_width = 4
```

.eslintrc.js
```
module.exports = {
	extends: ['airbnb-base', 'plugin:editorconfig/all'],
	plugins: ['editorconfig'],
};
```

**Comment by phanect** [comment]
Thanks for your report!

I considered to ignore no-tabs by `plugin:editorconfig/noconflict` and `plugin:editorconfig/all`, but in this case, adding `no-tabs: "off"` in your .eslintrc may be a better solution in my opinion.

While `editorconfig/indent` rule only checks indent, `no-tabs` rule seem to check tabs in other locations too. If I added `no-tabs: "off"` in `plugin:editorconfig/noconflict` and `plugin:editorconfig/all`, ESLint cannot check `non-indent` tabs and it is an unexpected behavior for users.

If it is difficult to add `no-tabs: "off"` in your .eslintrc in your usecase, let me know about your usecase.
